name: Build Mod

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Fix gradlew
        run: |
          sudo apt-get update
          sudo apt-get install -y dos2unix
          dos2unix gradlew
          chmod +x gradlew

      - name: Setup Java 
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build
        run: ./gradlew build --no-daemon

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: mod-jar
          path: build/libs/*.jar
